load("//build-tools/bazel:defs.bzl", "jjq_java_library")

jjq_java_library(
    name = "spi",
    srcs = [
        "Cardinality.java",
        "ConstantExpression.java",
        "Expression.java",
        "Function.java",
        "FunctionParameter.java",
        "FunctionSignature.java",
        "JqFunction.java",
        "JqLibrary.java",
        "Output.java",
        "package-info.java",
    ],
    release = 8,
    visibility = [
        "//jackson-jq-spi:__subpackages__",
        "//tests:__subpackages__",
    ],
    deps = [
        "//jackson-jq-json-provider",
        "//jackson-jq-spi/src/main/java/net/thisptr/jackson/jq/v2/spi/annotations",
        "//jackson-jq-spi/src/main/java/net/thisptr/jackson/jq/v2/spi/exception",
        "//jackson-jq-spi/src/main/java/net/thisptr/jackson/jq/v2/spi/path",
        "//jackson-jq-spi/src/main/java/net/thisptr/jackson/jq/v2/spi/version",
    ],
)
