load("//build-tools/bazel:defs.bzl", "jjq_java_test_suite")

jjq_java_test_suite(
    srcs = ["StackFrameValuesTest.java"],
    release = 8,
    visibility = ["//jackson-jq-core:__subpackages__"],
    deps = [
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/path",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/utils",
        "//jackson-jq-json-provider",
        "//jackson-jq-spi",
    ],
)
