load("//build-tools/bazel:defs.bzl", "jjq_java_library")

jjq_java_library(
    name = "comparator",
    srcs = ["JsonNodeComparator.java"],
    release = 8,
    visibility = [
        "//jackson-jq-core:__subpackages__",
        "//jackson-jq-fuzz:__subpackages__",
        "//tests:__subpackages__",
    ],
    deps = ["//jackson-jq-json-provider"],
)
