load("//build-tools/bazel:defs.bzl", "jjq_java_library")

jjq_java_library(
    name = "fieldaccess",
    srcs = [
        "AbstractFieldAccess.java",
        "BracketExtractFieldAccess.java",
        "BracketFieldAccess.java",
        "IdentifierFieldAccess.java",
        "StringFieldAccess.java",
    ],
    release = 8,
    visibility = ["//jackson-jq-core:__subpackages__"],
    deps = [
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/compile/freevars",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/exception",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/json",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/memory",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/misc",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/path/utils",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/tree",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/tree/literal",
        "//jackson-jq-json-provider",
        "//jackson-jq-spi",
    ],
)
