version: 2
updates:
  - package-ecosystem: "bazel"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/smoke-tests/osgi/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/smoke-tests/jpms/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/smoke-tests/graalvm/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/smoke-tests/java8/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/smoke-tests/quarkus/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
