load("//build-tools/bazel:defs.bzl", "jjq_java_library")

jjq_java_library(
    name = "collections",
    testonly = True,
    srcs = ["JsonList.java"],
    release = 17,
    visibility = ["//jackson-jq-json-provider:__subpackages__"],
    deps = ["//jackson-jq-json-provider/src/main/java/net/thisptr/jackson/jq/v2/json"],
)
