load("//build-tools/bazel:defs.bzl", "jjq_java_library")

jjq_java_library(
    name = "time",
    srcs = [
        "ModuleImpl.java",
    ],
    release = 8,
    visibility = ["//jackson-jq-ext-module-time:__subpackages__"],
    deps = [
        "//jackson-jq-ext-module-time/src/main/java/net/thisptr/jackson/jq/v2/ext/time/functions",
        "//jackson-jq-spi",
    ],
)
