load("//build-tools/bazel:defs.bzl", "jjq_java_library")

jjq_java_library(
    name = "ast",
    srcs = [
        "AbstractFieldAccessAstNode.java",
        "AbstractValueLiteralAstNode.java",
        "ArrayConstructionAstNode.java",
        "ArrayMatcherAstNode.java",
        "AstNode.java",
        "AstVisitor.java",
        "BinaryOpAstNode.java",
        "BooleanLiteralAstNode.java",
        "BracketExtractFieldAccessAstNode.java",
        "BracketFieldAccessAstNode.java",
        "BreakExpressionAstNode.java",
        "ConditionalAstNode.java",
        "ForeachExpressionAstNode.java",
        "FormattingFilterAstNode.java",
        "FunctionCallAstNode.java",
        "FunctionDefinitionAstNode.java",
        "IdentifierFieldAccessAstNode.java",
        "NegativeExpressionAstNode.java",
        "NullLiteralAstNode.java",
        "NumericLiteralAstNode.java",
        "ObjectConstructionAstNode.java",
        "ObjectMatcherAstNode.java",
        "ParenAstNode.java",
        "PatternMatcherAstNode.java",
        "PipedQueryAstNode.java",
        "RecursionOperatorAstNode.java",
        "ReduceExpressionAstNode.java",
        "SemicolonOperatorAstNode.java",
        "StringFieldAccessAstNode.java",
        "StringInterpolationAstNode.java",
        "StringLiteralAstNode.java",
        "ThisObjectAstNode.java",
        "TopLevelAstNode.java",
        "TryCatchAstNode.java",
        "TupleAstNode.java",
        "ValueMatcherAstNode.java",
        "VariableAccessAstNode.java",
    ],
    release = 8,
    visibility = ["//jackson-jq-core:__subpackages__"],
    deps = [
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/ast/operator",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/commons/pair",
    ],
)
