load("//build-tools/bazel:defs.bzl", "jjq_java_test_suite")

jjq_java_test_suite(
    srcs = [
        "RegexFunctionContractTest.java",
        "SubImplFunctionTest.java",
    ],
    release = 8,
    visibility = ["//jackson-jq-regex-impl-joni:__subpackages__"],
    deps = [
        "//jackson-jq-core",
        "//jackson-jq-json-provider",
        "//jackson-jq-json-provider-impl-jackson2",
        "//jackson-jq-regex-impl-joni/src/main/java/net/thisptr/jackson/jq/v2/regex/impl/joni",
        "//jackson-jq-spi",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:org_jruby_joni_joni",
    ],
)
