load("//build-tools/bazel:defs.bzl", "jjq_java_test_suite")

jjq_java_test_suite(
    srcs = ["Fastjson2JsonProviderContractTest.java"],
    release = 8,
    visibility = ["//jackson-jq-json-provider-impl-fastjson2:__subpackages__"],
    deps = [
        "//jackson-jq-json-provider",
        "//jackson-jq-json-provider:contract-test",
        "//jackson-jq-json-provider-impl-fastjson2/src/main/java/net/thisptr/jackson/jq/v2/json/impl/fastjson2",
        "@maven//:com_alibaba_fastjson2_fastjson2",
    ],
)
