load("//build-tools/bazel:defs.bzl", "jjq_java_library")

jjq_java_library(
    name = "joni",
    srcs = glob(["*.java"]),
    release = 17,
    visibility = ["//jackson-jq-ext-module-joni:__subpackages__"],
    deps = [
        "//jackson-jq-json-io",
        "//jackson-jq-json-provider",
        "//jackson-jq-spi",
        "@maven//:org_jruby_jcodings_jcodings",
        "@maven//:org_jruby_joni_joni",
    ],
)
