load("//build-tools/bazel:defs.bzl", "jjq_java_library")

jjq_java_library(
    name = "builtins",
    srcs = [
        "AbstractAtFormattingFunction.java",
        "AbstractKeysFunction.java",
        "AbstractMaxByFunction.java",
        "AbstractPureJsonArgumentFunction.java",
        "AbstractStartsEndsWithFunction.java",
        "AbstractTrimStrFunction.java",
        "AtBase64Function.java",
        "AtBase64dFunction.java",
        "AtHtmlFunction.java",
        "AtShFunction.java",
        "AtUriFunction.java",
        "BuiltinsFunction.java",
        "ContainsFunction.java",
        "DelPathsFunction.java",
        "EmptyFunction.java",
        "EndsWithFunction.java",
        "ErrorFunction.java",
        "ExplodeFunction.java",
        "FromDateIso8601Function.java",
        "FromEntriesFunction.java",
        "FromJsonFunction.java",
        "GetPathFunction.java",
        "GroupByFunction.java",
        "HasFunction.java",
        "ImplodeFunction.java",
        "IndexFunction.java",
        "IndicesFunction.java",
        "InfiniteFunction.java",
        "IsEmptyFunction.java",
        "IsInfiniteFunction.java",
        "IsNanFunction.java",
        "IsNormalFunction.java",
        "JoinFunction.java",
        "KeysFunction.java",
        "KeysUnsortedFunction.java",
        "LTrimStrFunction.java",
        "LengthFunction.java",
        "MaxByFunction.java",
        "MinByFunction.java",
        "NanFunction.java",
        "NotFunction.java",
        "NowFunction.java",
        "PathFunction.java",
        "PathsFunction.java",
        "RIndexFunction.java",
        "RTrimStrFunction.java",
        "RangeFunction.java",
        "ReverseFunction.java",
        "SetPathFunction.java",
        "SortByFunction.java",
        "SplitFunction.java",
        "StartsWithFunction.java",
        "ToDateIso8601Function.java",
        "ToEntriesFunction.java",
        "ToJsonFunction.java",
        "ToNumberFunction.java",
        "ToStringFunction.java",
        "TypeFunction.java",
        "Utf8ByteLengthFunction.java",
    ],
    release = 8,
    visibility = ["//jackson-jq-core:__subpackages__"],
    deps = [
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/function/loaders",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/commons/collection",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/commons/pair",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/commons/range",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/commons/strings",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/exception",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/function/utils",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/json",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/json/comparator",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/json/operations",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/misc",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/path/utils",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/tree/binaryop",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/version",
        "//jackson-jq-json-provider",
        "//jackson-jq-spi",
    ],
)
