load("//build-tools/bazel:defs.bzl", "jjq_java_library")

jjq_java_library(
    name = "functions",
    srcs = [
        "DebugExprFunction.java",
        "DebugScopeFunction.java",
        "DumpExprFunction.java",
    ],
    release = 8,
    visibility = ["//jackson-jq-ext-module-debug:__subpackages__"],
    deps = [
        "//jackson-jq-json-provider",
        "//jackson-jq-spi",
    ],
)
