load("//build-tools/bazel:defs.bzl", "jjq_java_mrjar", "jjq_maven_artifact")

package(default_visibility = ["//visibility:public"])

jjq_java_mrjar(
    name = "jackson-jq-regex-impl-joni-mrjar",
    osgi = True,
    packages = [
        "//jackson-jq-regex-impl-joni/src/main/java:module-info",
        "//jackson-jq-regex-impl-joni/src/main/java/net/thisptr/jackson/jq/v2/regex/impl/joni",
    ],
    resources = ["src/main/resources/META-INF/native-image/net.thisptr.jackson.jq.v2/jackson-jq-regex-impl-joni/native-image.properties"],
)

jjq_maven_artifact(
    name = "jackson-jq-regex-impl-joni",
    artifact = ":jackson-jq-regex-impl-joni-mrjar",
)
