load("//build-tools/bazel:defs.bzl", "jjq_java_mrjar", "jjq_maven_artifact")

package(default_visibility = ["//visibility:public"])

jjq_java_mrjar(
    name = "jackson-jq-spi-mrjar",
    osgi = True,
    packages = [
        "//jackson-jq-spi/src/main/java:module-info",
        "//jackson-jq-spi/src/main/java/net/thisptr/jackson/jq/v2/spi",
        "//jackson-jq-spi/src/main/java/net/thisptr/jackson/jq/v2/spi/annotations",
        "//jackson-jq-spi/src/main/java/net/thisptr/jackson/jq/v2/spi/exception",
        "//jackson-jq-spi/src/main/java/net/thisptr/jackson/jq/v2/spi/module",
        "//jackson-jq-spi/src/main/java/net/thisptr/jackson/jq/v2/spi/path",
        "//jackson-jq-spi/src/main/java/net/thisptr/jackson/jq/v2/spi/type",
        "//jackson-jq-spi/src/main/java/net/thisptr/jackson/jq/v2/spi/version",
    ],
)

jjq_maven_artifact(
    name = "jackson-jq-spi",
    artifact = ":jackson-jq-spi-mrjar",
)
