load("//build-tools/bazel:defs.bzl", "jjq_java_module_info")

jjq_java_module_info(
    module_name = "net.thisptr.jackson.jq.v2.core",
    module_packages = [
        "//jackson-jq-core:core-sources",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/ast",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/ast/operator",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/ast/parser",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/builtins",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/builtins/filters",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/builtins/library",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/builtins/math",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/commons/collection",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/commons/pair",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/commons/range",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/commons/strings",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/compile/freevars",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/exception",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/function/loaders",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/json",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/json/comparator",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/memory",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/misc",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/module",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/path",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/path/utils",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/tree",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/tree/binaryop",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/tree/binaryop/assignment",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/tree/binaryop/comparison",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/tree/fieldaccess",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/tree/literal",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/tree/matcher",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/tree/matcher/matchers",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/utils",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/function",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/function/loaders",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/module",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/version",
    ],
    release = 9,
    visibility = ["//jackson-jq-core:__pkg__"],
    deps = [
        "//jackson-jq-json-provider",
        "//jackson-jq-spi",
    ],
)
