load("//build-tools/bazel:defs.bzl", "jjq_java_module_info")

jjq_java_module_info(
    module_name = "net.thisptr.jackson.jq.v2.ext.module.binary",
    module_packages = [
        "//jackson-jq-ext-module-binary/src/main/java/net/thisptr/jackson/jq/v2/ext/binary",
    ],
    release = 9,
    visibility = ["//jackson-jq-ext-module-binary:__pkg__"],
    deps = [
        "//jackson-jq-json-provider",
        "//jackson-jq-spi",
    ],
)
