load("//build-tools/bazel:defs.bzl", "jjq_java_module_info")

jjq_java_module_info(
    module_name = "net.thisptr.jackson.jq.v2.ext.module.zstd",
    module_packages = [
        "//jackson-jq-ext-module-zstd/src/main/java/net/thisptr/jackson/jq/v2/ext/zstd",
    ],
    release = 9,
    visibility = ["//jackson-jq-ext-module-zstd:__pkg__"],
    deps = [
        "//jackson-jq-json-provider",
        "//jackson-jq-spi",
        "@maven//:com_github_luben_zstd_jni",
    ],
)
