load("//build-tools/bazel:defs.bzl", "jjq_java_test_suite")

jjq_java_test_suite(
    srcs = [
        "UuidUtilsTest.java",
    ],
    release = 8,
    visibility = ["//jackson-jq-ext-module-uuid:__subpackages__"],
    deps = ["//jackson-jq-ext-module-uuid/src/main/java/net/thisptr/jackson/jq/v2/ext/uuid/internal/misc"],
)
