load("//build-tools/bazel:defs.bzl", "jjq_java_mrjar", "jjq_maven_artifact")

package(default_visibility = ["//visibility:public"])

jjq_java_mrjar(
    name = "jackson-jq-json-provider-impl-gson-mrjar",
    osgi = True,
    packages = ["//jackson-jq-json-provider-impl-gson/src/main/java/net/thisptr/jackson/jq/v2/json/impl/gson"],
    release_overlays = {9: ["//jackson-jq-json-provider-impl-gson/src/main/java9:module-info"]},
)

jjq_maven_artifact(
    name = "jackson-jq-json-provider-impl-gson",
    artifact = ":jackson-jq-json-provider-impl-gson-mrjar",
)
