load("//build-tools/bazel:defs.bzl", "jjq_java_module_info")

jjq_java_module_info(
    module_name = "net.thisptr.jackson.jq.v2.ext.module.uri",
    module_packages = [
        "//jackson-jq-ext-module-uri/src/main/java/net/thisptr/jackson/jq/v2/ext/uri",
        "//jackson-jq-ext-module-uri/src/main/java/net/thisptr/jackson/jq/v2/ext/uri/functions",
        "//jackson-jq-ext-module-uri/src/main/java/net/thisptr/jackson/jq/v2/ext/uri/internal/misc",
    ],
    release = 9,
    visibility = ["//jackson-jq-ext-module-uri:__pkg__"],
    deps = [
        "//jackson-jq-json-provider",
        "//jackson-jq-spi",
    ],
)
