load("//build-tools/bazel:defs.bzl", "jjq_java_library")

jjq_java_library(
    name = "module",
    srcs = [
        "NullModuleLoader.java",
        "SimpleModule.java",
        "SimpleModuleMeta.java",
    ],
    release = 8,
    visibility = ["//jackson-jq-core:__subpackages__"],
    deps = [
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/ast",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/ast/impls",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/utils",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/module",
        "//jackson-jq-json-provider",
        "//jackson-jq-spi",
    ],
)
