load("//build-tools/bazel:defs.bzl", "jjq_java_library")

jjq_java_library(
    name = "jackson2",
    srcs = [
        "Jackson2JsonProviderImpl.java",
        "JsonQueryJacksonModule.java",
    ],
    release = 8,
    visibility = ["//jackson-jq-json-provider-impl-jackson2:__subpackages__"],
    deps = [
        "//jackson-jq-json-provider",
        "@maven//:com_fasterxml_jackson_core_jackson_core",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
    ],
)
