load("//build-tools/bazel:defs.bzl", "jjq_java_module_info")

jjq_java_module_info(
    module_name = "net.thisptr.jackson.jq.v2.json.impl.jackson2",
    module_packages = [
        "//jackson-jq-json-provider-impl-jackson2/src/main/java/net/thisptr/jackson/jq/v2/json/impl/jackson2",
    ],
    release = 9,
    visibility = ["//jackson-jq-json-provider-impl-jackson2:__pkg__"],
    deps = [
        "//jackson-jq-json-provider",
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:com_fasterxml_jackson_core_jackson_core",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
    ],
)
