load("//build-tools/bazel:defs.bzl", "jjq_java_mrjar", "jjq_maven_artifact")

package(default_visibility = ["//visibility:public"])

jjq_java_mrjar(
    name = "jackson-jq-ext-module-fs-mrjar",
    osgi = True,
    packages = [
        "//jackson-jq-ext-module-fs/src/main/java:module-info",
        "//jackson-jq-ext-module-fs/src/main/java/net/thisptr/jackson/jq/v2/ext/fs",
        "//jackson-jq-ext-module-fs/src/main/java/net/thisptr/jackson/jq/v2/ext/fs/functions",
    ],
)

jjq_maven_artifact(
    name = "jackson-jq-ext-module-fs",
    artifact = ":jackson-jq-ext-module-fs-mrjar",
)
