load("//build-tools/bazel:defs.bzl", "jjq_java_library")

jjq_java_library(
    name = "tree",
    srcs = [
        "ArrayConstruction.java",
        "AssignPipeComponent.java",
        "BreakExpression.java",
        "Conditional.java",
        "FieldConstruction.java",
        "FixedInputExpression.java",
        "ForeachExpression.java",
        "IdentifierKeyFieldConstruction.java",
        "JsonQueryKeyFieldConstruction.java",
        "LabelPipeComponent.java",
        "NegativeExpression.java",
        "ObjectConstruction.java",
        "PipeComponent.java",
        "PipedQuery.java",
        "PrecomputedConstantExpression.java",
        "RecursionOperator.java",
        "ReduceExpression.java",
        "SemicolonOperator.java",
        "StringInterpolation.java",
        "StringKeyFieldConstruction.java",
        "ThisObject.java",
        "TopLevelExpression.java",
        "TransformPipeComponent.java",
        "TryCatch.java",
        "Tuple.java",
    ],
    release = 8,
    visibility = ["//jackson-jq-core:__subpackages__"],
    deps = [
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/ast/impls",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/commons/pair",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/compile/freevars",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/exception",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/json",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/memory",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/misc",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/path",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/path/utils",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/tree/matcher",
        "//jackson-jq-json-provider",
        "//jackson-jq-spi",
    ],
)
