load("//build-tools/bazel:defs.bzl", "jjq_java_test_suite")

jjq_java_test_suite(
    srcs = [
        "Jackson3JsonProviderContractTest.java",
    ],
    release = 17,
    visibility = ["//jackson-jq-json-provider-impl-jackson3:__subpackages__"],
    deps = [
        "//jackson-jq-json-provider",
        "//jackson-jq-json-provider:contract-test",
        "//jackson-jq-json-provider-impl-jackson3/src/main/java/net/thisptr/jackson/jq/v2/json/impl/jackson3",
        "@maven//:tools_jackson_core_jackson_core",
        "@maven//:tools_jackson_core_jackson_databind",
    ],
)
