load("//build-tools/bazel:defs.bzl", "jjq_java_library")

jjq_java_library(
    name = "exception",
    srcs = [
        "JsonQueryException.java",
        "package-info.java",
    ],
    release = 8,
    visibility = [
        "//jackson-jq-spi:__subpackages__",
        "//tests:__subpackages__",
    ],
    deps = ["//jackson-jq-json-provider"],
)
