load("//build-tools/bazel:defs.bzl", "jjq_java_module_info")

jjq_java_module_info(
    module_name = "net.thisptr.jackson.jq.v2.json.impl.jakarta",
    module_packages = [
        "//jackson-jq-json-provider-impl-jakarta/src/main/java/net/thisptr/jackson/jq/v2/json/impl/jakarta",
    ],
    release = 11,
    visibility = ["//jackson-jq-json-provider-impl-jakarta:__pkg__"],
    deps = [
        "//jackson-jq-json-provider",
        "@maven//:jakarta_json_jakarta_json_api",
    ],
)
