load("//build-tools/bazel:defs.bzl", "jjq_java_test_suite")

jjq_java_test_suite(
    srcs = [
        "JsonNodeComparatorTest.java",
        "JsonNodeUtilsTest.java",
    ],
    release = 8,
    visibility = ["//jackson-jq-core:__subpackages__"],
    deps = [
        "//jackson-jq-core",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/comparator",
        "//jackson-jq-json-provider",
        "//jackson-jq-json-provider-impl-jackson2",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
    ],
)
