load("//build-tools/bazel:defs.bzl", "jjq_java_library")

jjq_java_library(
    name = "assignment",
    srcs = [
        "AbstractComplexAssignment.java",
        "Assignment.java",
        "ComplexAlternativeAssignment.java",
        "ComplexDivideAssignment.java",
        "ComplexMinusAssignment.java",
        "ComplexModuloAssignment.java",
        "ComplexMultiplyAssignment.java",
        "ComplexPlusAssignment.java",
        "UpdateAssignment.java",
    ],
    release = 8,
    visibility = ["//jackson-jq-core:__subpackages__"],
    deps = [
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/exception",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/json",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/json/comparator",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/json/operations",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/memory",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/path/utils",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/internal/tree/binaryop",
        "//jackson-jq-core/src/main/java/net/thisptr/jackson/jq/v2/core/version",
        "//jackson-jq-json-provider",
        "//jackson-jq-spi",
    ],
)
