load("//build-tools/bazel:defs.bzl", "jjq_java_test_suite")

jjq_java_test_suite(
    srcs = ["Jep540JsonProviderContractTest.java"],
    jvm_flags = ["--enable-preview"],
    release = 26,
    visibility = ["//jackson-jq-json-provider-impl-jep540:__subpackages__"],
    deps = [
        "//jackson-jq-json-provider",
        "//jackson-jq-json-provider:contract-test",
        "//jackson-jq-json-provider-impl-jep540/src/main/java/net/thisptr/jackson/jq/v2/json/impl/jep540",
        "@jep540_sources//:jdk_incubator_json",
    ],
)
