load("//build-tools/bazel:defs.bzl", "jjq_java_library")

jjq_java_library(
    name = "fastjson2",
    srcs = ["Fastjson2JsonProviderImpl.java"],
    release = 8,
    visibility = ["//jackson-jq-json-provider-impl-fastjson2:__subpackages__"],
    deps = [
        "//jackson-jq-json-provider",
        "@maven//:com_alibaba_fastjson2_fastjson2",
    ],
)
