package net.thisptr.jackson.jq.v2.spi.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Repeatable;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Declares the name, arity, and applicable jq versions under which an annotated
 * {@code net.thisptr.jackson.jq.v2.spi.Function} implementation is registered.
 * <p>
 * This annotation only supplies metadata; it does not by itself make the annotated class
 * discoverable. The class must <em>also</em> be registered so that
 * {@link java.util.ServiceLoader#load(Class)} finds it:
 * <ul>
 * <li><b>Classpath</b>: a {@code META-INF/services/net.thisptr.jackson.jq.v2.spi.Function} entry
 *     naming the implementation, typically generated by
 *     {@code @com.google.auto.service.AutoService(Function.class)}.</li>
 * <li><b>JPMS</b>: a {@code provides net.thisptr.jackson.jq.v2.spi.Function with ...;} declaration
 *     in {@code module-info.java}.</li>
 * <li><b>OSGi</b>: {@code Provide-Capability}/{@code Require-Capability} bundle headers for the
 *     ServiceLoader Mediator specification ({@code osgi.serviceloader} plus
 *     {@code osgi.extender=osgi.serviceloader.registrar}).</li>
 * </ul>
 * A single class may carry multiple {@code @FunctionRegistration} annotations (see
 * {@link Repeatable} / {@link FunctionRegistrations}) to register under several names or arities.
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Repeatable(FunctionRegistrations.class)
public @interface FunctionRegistration {
	/**
	 * Returns the registered function name.
	 *
	 * @return the registered function name
	 */
	String name();

	/**
	 * The number of arguments this function takes. A negative value registers
	 * the function as variadic: it is bound under {@code name} alone (no {@code /nargs} suffix), matching the arity-agnostic
	 * fallback which looks up {@code name/nargs} first and falls back to bare
	 * {@code name} for any arity.
	 *
	 * @return the arity, or a negative value if variadic
	 */
	int nargs();

	/**
	 * The jq versions this registration applies to. Defaults to all versions.
	 *
	 * @return the applicable jq version range
	 */
	VersionRangeSpec version() default @VersionRangeSpec;
}
