package net.thisptr.jackson.jq.v2.spi.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Repeatable;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Declares the import path under which an annotated
 * {@code net.thisptr.jackson.jq.v2.spi.module.Module} implementation is registered.
 * <p>
 * As with {@link FunctionRegistration}, this annotation only supplies metadata; the class must
 * also be made discoverable via {@link java.util.ServiceLoader#load(Class)} -- a
 * {@code META-INF/services/net.thisptr.jackson.jq.v2.spi.module.Module} entry (classpath,
 * typically generated by {@code @com.google.auto.service.AutoService(Module.class)}), a
 * {@code provides ... Module with ...;} declaration ({@code module-info.java}), or equivalent
 * OSGi ServiceLoader Mediator {@code Provide-Capability}/{@code Require-Capability} bundle
 * headers. A single class may carry multiple {@code @ModuleRegistration} annotations (see
 * {@link Repeatable} / {@link ModuleRegistrations}) to register under several paths.
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Repeatable(ModuleRegistrations.class)
public @interface ModuleRegistration {
	/**
	 * Returns the registered module import path, e.g. {@code "foo/bar"}.
	 *
	 * @return the registered module import path, e.g. {@code "foo/bar"}
	 */
	String path();
}
