load("//build-tools/bazel:defs.bzl", "jjq_java_library")

jjq_java_library(
    name = "exception",
    srcs = [
        "ExceptionMessages.java",
        "IllegalJsonArgumentException.java",
        "IllegalJsonInputException.java",
        "JsonQueryBreakException.java",
        "JsonQueryTypeException.java",
        "JsonQueryUndefinedBehaviorException.java",
        "JsonQueryUserException.java",
    ],
    release = 8,
    visibility = ["//jackson-jq-core:__subpackages__"],
    deps = [
        "//jackson-jq-json-provider",
        "//jackson-jq-spi",
    ],
)
