load("//build-tools/bazel:defs.bzl", "jjq_java_library")

jjq_java_library(
    name = "math",
    srcs = [
        "Atan2Function.java",
        "PowFunction.java",
    ],
    release = 8,
    visibility = ["//jackson-jq-core:__subpackages__"],
    deps = [
        "//jackson-jq-core:core-sources",
        "//jackson-jq-json-provider",
        "//jackson-jq-spi",
    ],
)
